Fix: ansible requires python > 3.10
ERROR: 9.0.1 Requires-Python >=3.10; 9.1.0
Requires-Python >=3.10; 9.2.0 Requires-Python >=3.10

Signed-off-by: Anil Belur <abelur@linuxfoundation.org>
Change-Id: I46d78f3e77a5cad0d7ce1cc1074fc8e7ac53c3d0