Fix: Change powertools repoid to lowercase
The repoids are renamed with CentOS 8.3 update breaks the packer
builds. Now the correct repoid to use is 'powertools' instead
of 'PowerTools'

Error: No matching repo to modify: PowerTools.

Ref:
https: //wiki.centos.org/Manuals/ReleaseNotes/CentOS8.2011#Yum_repo_file_and_repoid_changes
Issue: RELENG-3710
Change-Id: I43b943ddfc38facaa8c02f2d6ee98254e7ee3241
Signed-off-by: Anil Belur <abelur@linuxfoundation.org>